apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
data:
  USE_DOCKER: "yes"
  DJANGO_ADMIN_URL: "^admin/"
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_SECRET_KEY: "CHANGEME"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,django,sixfeetup.com"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,https://sixfeetup.com"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  POSTGRES_USER: "awesome"
  POSTGRES_PASSWORD: "CHANGEME"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  DATABASE_URL: "psql://awesome:CHANGEME@postgres:5432/awesome"
  REDIS_URL: "redis://redis:6379/1"
