apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celeryworker
          image: backend:latest
          command: ["celery", "-A", "{{ cookiecutter.project_slug }}", "worker", "-E", "-l", "info"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
        - name: celerybeat
          image: backend:latest
          command: ["celery", "-A", "{{ cookiecutter.project_slug }}", "beat"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
        - name: flower
          image: backend:latest
          command: ["celery", "-A", "{{ cookiecutter.project_slug }}", "flower"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
