apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          ports:
            - name: http-server
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DJANGO_ADDRESS
              value: backend:8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secrets-config
