apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./app.configmap.yaml
- ./django.yaml
{% if cookiecutter.create_nextjs_frontend == "y" %}
- ./frontend.yaml{% endif %}
- ./redis.yaml
{%- if cookiecutter.use_celery == "y" %}
- ./celery.yaml{%- endif %}
