image: python:3.10

definitions:
  services:
    docker:
      memory: 3072
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: {{cookiecutter.project_slug}}
        POSTGRES_USER: {{cookiecutter.project_slug}}
        POSTGRES_PASSWORD: TESTPASSWORD
{% if cookiecutter.use_celery == 'y' %}
    redis:
      image: redis:stable
{% endif %}

  steps:
    - step: &backend-tests
        name: Backend Tests
        caches:
          - pip
        script:
          - export DATABASE_URL=postgres://{{cookiecutter.project_slug}}:TESTPASSWORD@127.0.0.1:5432/{{cookiecutter.project_slug}}
{% if cookiecutter.use_celery == 'y' %}
          - export CELERY_BROKER_URL=redis://127.0.0.1:6379/0
{% endif %}
          - make backend-test

        services:
{% if cookiecutter.use_celery == 'y' %}
          - redis
{% endif %}
          - postgres

    - step: &check-lint-and-formatting
        name: Check lint and formatting
        caches:
          - pip
        script:
          - make check-lint-and-formatting

{% if cookiecutter.create_react_frontend == 'y' %}
    - step: &check-lint-and-test-frontend
        name: Frontend Lint & Typecheck & Test
        image: node:16-bullseye
        caches:
          - node
        script:
          - make check-lint-and-test-frontend
{% endif %}

pipelines:
  default:
    - parallel:
      - step: *check-lint-and-formatting
{% if cookiecutter.create_react_frontend == 'y' %}
      - step: *check-lint-and-test-frontend
{% endif %}
      - step: *backend-tests
