version: '3.7'
volumes:
  local_postgres_data_{{ cookiecutter.project_slug }}: {}
  local_postgres_data_{{ cookiecutter.project_slug }}_backups: {}
services:
  db:
    image: 'postgres:14'
    volumes:
      - 'local_postgres_data_{{ cookiecutter.project_slug }}:/var/lib/postgresql/data'
      - 'local_postgres_data_{{ cookiecutter.project_slug }}_backups:/backups'
    env_file:
      - backend/local/environment
  django:
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: 'python manage.py runserver 0.0.0.0:8000'
    # command: 'gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - migrate
      - mailhog
      {% if cookiecutter.use_celery == 'y' %}
      - celerybeat
      - celeryworker
      - flower
      {% endif %}
  migrate:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: python manage.py migrate
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
  {% if cookiecutter.use_celery == 'y' %}
  celeryworker:
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: '/app/bin/celery -A {{ cookiecutter.project_slug }} worker -E -l info'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
      - redis
  celerybeat:
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: '/app/bin/celery -A {{ cookiecutter.project_slug }} beat'
    volumes:
      - '.backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
      - redis
  flower:
    image: '{{ cookiecutter.project_slug }}_local_django:dev'
    command: '/app/bin/celery -A {{ cookiecutter.project_slug }} flower'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
      - redis
  {% endif %}
  {% if cookiecutter.create_frontend == 'y' %}
  frontend:
    image: '{{ cookiecutter.project_slug }}_local_frontend:dev'
    user: node
    working_dir: /app
    environment:
      - BROWSER=none
    command: npm run dev
    volumes:
      - '/app/node_modules'
      - './frontend:/app'
    stdin_open: true
  {% endif %}
  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
  {% if cookiecutter.use_celery == 'y' %}
  redis:
    image: 'redis:latest'
  {% endif %}
