apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: {{ cookiecutter.project_slug }}_local_django
      context: backend
      sync:
        infer:
          - "**/*"
      docker:
        buildArgs:
          DEVEL: "yes"
    - image: {{ cookiecutter.project_slug }}_local_frontend
      context: frontend
      sync:
        infer:
          - "**/*"

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
      - ./k8s/*
#  helm:
#    releases:
#      - name: {{ cookiecutter.project_slug }}-release
#        chartPath: helm
#        namespace: {{ cookiecutter.project_slug }}
#    flags:
#      install: ["--create-namespace"]
  statusCheckDeadlineSeconds: 60

portForward:
  - resourceType: service
    resourceName: django
    port: 8000
  - resourceType: service
    resourceName: mailhog
    port: 8025
  - resourceType: service
    resourceName: frontend
    port: 3000
  - resourceType: service
    resourceName: postgres
    port: 5432
