# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: update

requirements:
  - "requirements.txt"
  - "requirements.in"
  - "{{cookiecutter.project_slug}}/backend/requirements/base.in"
  - "{{cookiecutter.project_slug}}/backend/requirements/local.in"
  - "{{cookiecutter.project_slug}}/backend/requirements/production.in"
  - "{{cookiecutter.project_slug}}/backend/requirements/tests.in"
