#!/bin/bash

docker run --rm -it -v .:/home/scaf/out \
  -e HOST_UID="$(id -u)" \
  -e HOST_GID="$(id -g)" \
  scaf:latest \
  cookiecutter ${1:-https://github.com/sixfeetup/cookiecutter-sixiedjango/}
