#!/usr/bin/env bash

# set python command
if command -v python &>/dev/null; then
    PYTHON_CMD=python
elif command -v python3 &>/dev/null; then
    PYTHON_CMD=python3
else
    echo "Missing python3 command. Please install python3."
    exit 1;
fi


# Ensure at least one argument is provided (for project_slug)
if [ $# -lt 1 ]; then
  echo "Usage: $0 project_slug [OPTIONS] [TEMPLATE]"
  exit 1
fi

# The first argument is always the project slug
PROJECT_SLUG="$1"

# Validate the project slug
if ! [[ $PROJECT_SLUG =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Error: PROJECT_SLUG should only contain alphanumeric characters, underscores and hyphens."
    exit 1
fi

# Remove the project_slug from the argument list
shift
CLUSTER_SLUG=${PROJECT_SLUG//_/-}
COPIER_SLUG=${PROJECT_SLUG//-/_}

# Assume the last argument is the template URL unless it starts with a dash
REPO_URL=""
if [ $# -gt 0 ]; then
  LAST_ARG="${@: -1}"
  if [[ $LAST_ARG == -* ]]; then
    COPIER_OPTIONS="$@"
  else
    REPO_URL="$LAST_ARG"
    # Remove the last argument (the REPO_URL) from the options
    COPIER_OPTIONS="${@:1:$(($#-1))}"
  fi
else
  COPIER_OPTIONS=""
fi

# If no repo URL was provided, ask for template selection
if [ -z "$REPO_URL" ]; then
  echo "Please choose a template:"
  echo "1) SFU Full Stack Template"
  echo "2) AWS Lambda App Template"
  echo -n "Enter the number corresponding to your choice (1 or 2): "
  read -r template_choice

  case $template_choice in
    1)
      REPO_URL="https://github.com/sixfeetup/scaf-fullstack-template.git"
      ;;
    2)
      REPO_URL="https://github.com/sixfeetup/scaf-aws-lambda-app-template.git"
      ;;
    *)
      echo "Invalid choice. Using default SFU Full Stack Template."
      REPO_URL="https://github.com/sixfeetup/scaf-aws-lambda-app-template.git"
      ;;
  esac
fi


party_popper() {
  for i in {1..4}; do
      echo -ne "\r🎉 POP! 💥"
      sleep 0.3
      echo -ne "\r💥 POP! 🎉"
      sleep 0.3
  done
  echo -e "\r🎊 Congrats! Your $PROJECT_SLUG project is ready! 🎉"
  echo
  echo "To get started, run:"
  echo "cd $PROJECT_SLUG"
  echo "tilt up"
  echo
}


echo "COPIER_OPTIONS: $COPIER_OPTIONS"
echo "REPO_URL: $REPO_URL"


echo "Creating your project..."
uv run --with isort,black,copier copier copy $COPIER_OPTIONS $REPO_URL . --trust -d "is_project_slug=$COPIER_SLUG"

# Check if copier was successful
if [ $? -eq 0 ]; then
  kind create cluster --name $CLUSTER_SLUG
  cd $COPIER_SLUG
  make compile
  echo "Dependencies compiled successfully."
  pwd
  echo "Performing initial commit."
  git add .
  git commit -m "Initial commit"
  party_popper
else
  echo "Failed to create project."
  exit 1
fi
