name: Main Workflow

on: [ push, pull_request ]

jobs:
  check-lint-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check lint and formatting
        run: make check-lint-and-formatting
{% if cookiecutter.create_react_frontend == 'y' %}
  check-lint-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Frontend Lint & Typecheck & Test
        run: make check-lint-and-test-frontend
{% endif %}
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: {{ cookiecutter.project_slug }}
          POSTGRES_USER: {{ cookiecutter.project_slug }}
          POSTGRES_PASSWORD: TESTPASSWORD
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

{% if cookiecutter.use_celery == 'y' %}
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
{% endif %}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run backend tests
        run: make backend-test
        env:
          DATABASE_URL: postgres://{{ cookiecutter.project_slug }}:TESTPASSWORD@localhost:5432/{{ cookiecutter.project_slug }}
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
{% if cookiecutter.use_celery == 'y' %}          CELERY_BROKER_URL: redis://127.0.0.1:6379/0{% endif %}