apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts 
    targetRevision: 28.0.0
    helm:
      releaseName: traefik
      parameters:
      - name: "service.type"
        value: NodePort
      - name: "ports.web.nodePort"
        value: "30080"
      - name: "ports.websecure.nodePort"
        value: "30443"
      - name: "deployment.kind"
        value: DaemonSet
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
