apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.name }}-pv
  labels:
    type: local
    environment: dev
spec:
  storageClassName: default
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/{{ .Values.postgres.name }}-data
