apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.name }}-pv
  labels:
    type: local
    environment: dev
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/{{ .Values.appName }}-{{ .Values.postgres.name }}-data
