apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ cookiecutter.project_slug }}
    tier: db
    environment: dev
spec:
  ports:
    - name: "port-5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ cookiecutter.project_slug }}
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: {{ cookiecutter.project_slug }}
    tier: db
    environment: dev
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.project_slug }}
      tier: db
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_slug }}
        tier: db
    spec:
      containers:
        - name: postgres
          image: postgres:12.7
          ports:
            - containerPort: 5432
              name: "port-5432"
          envFrom:
          - configMapRef:
              name: django-config
          volumeMounts:
            - name: postgres-db
              mountPath: /var/lib/postgresql/data
          # readinessProbe:
          #   exec:
          #     command:
          #       - bash
          #       - "-c"
          #       - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          # livenessProbe:
          #   exec:
          #     command:
          #       - bash
          #       - "-c"
          #       - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    environment: dev
spec:
  storageClassName: default
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    type: local
    environment: dev
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  volumeName: postgres-pv
