apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  template:
      spec:
        containers:
        - name: django
          env:
            - name: DOCKER_GATEWAY_IP # used for debugger to reach out to host machine
              value: "172.17.0.1"
