apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
- ../../base/argocd
- ../../base/cert-manager
- ../../base/cloudnative-pg
- ../../base/ingress
- ../../base/kube-prometheus-stack
- ../../base/local-path-provisioner
- ../../base/reflector
- ../../base/sealed-secrets
- ../../base/traefik
- ../../base/{{ cookiecutter.project_slug }}
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /spec/source/targetRevision
      value: main
    - op: replace
      path: /spec/source/path
      value: argocd/prod/ingress
  target:
    kind: Application
    name: ingress
